# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: ADA-FS
title: ADA-FS
description: Advanced Data Placement via Ad-hoc File Systems at Extreme Scale
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username: ada-fs

avatar: https://raw.githubusercontent.com/ada-fs/ada-fs.github.io/master/img/ada-fs-github.png

#highlighter: pygments

# Build settings
markdown: redcarpet

footer-links:
    github: ada-fs
    rss: ada-fs
    email: ada-fs-all@fusionforge.zih.tu-dresden.de


exclude:
    - README.md
    - LICENSE
